### ISSUE TITLE
"Connection refused" is unhandeled

### ISSUE THREAD

**Issue by braingained** [kgaughan/uwhoisd#21]
Sometimes the deamon needs to be restarted because of the following unhandeled Exception:

[2016/05/10 16:07:59] {diesel} ERROR|-- Unhandled Exception in local loop <<functools.partial object at 0x7fb82091c260>> --
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/diesel/core.py", line 195, in run
    self.loop_callable(_self.args, *_self.kw)
  File "/usr/local/lib/python2.7/dist-packages/uwhoisd/net.py", line 71, in respond
    diesel.send("; Connection refused by downstream server\r\n")
  File "/usr/local/lib/python2.7/dist-packages/diesel/core.py", line 86, in send
    return current_loop.send(_args, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/diesel/core.py", line 538, in send
    conn = self.check_connection()
  File "/usr/local/lib/python2.7/dist-packages/diesel/core.py", line 534, in check_connection
    raise ConnectionClosed("Cannot complete TCP socket operation: associated connection is closed")
ConnectionClosed: Cannot complete TCP socket operation: associated connection is closed
[2016/05/10 16:07:59] {diesel} ERROR|internal error: expected empty read on disconnected socket
2016-05-10 18:07:55,131 INFO:uwhoisd    Connection refused

**Comment by kgaughan** [comment]
Thanks for the report! I'm currently rewriting the core as I have time to do so to remove the dependency on diesel. While I'm doing that, I'll add a test to the test suite to check for this particular issue.
